#!/bin/bash
# Score stored XIVO trajectories with the *same* evaluator, window and groundtruth
# that score_openvins.py uses, so the two systems can be put in one table.
#
# Usage:
#   ./score_xivo_reference.sh [xivo-result-dir] [gt-dir] [max_difference]
#
# Defaults to XIVO's best mono+IMU config from RESULTS.md
# (results/final/triangulation_configs/sweep_dlt_nodesc) and the groundtruth
# regenerated by run_openvins.sh into experiments/results/ov_accuracy/gt.
#
# XIVO writes one file per sequence named tumvi_<seq>_cam0 (that is the estimate;
# _bench is a 2-line header, see the workspace notes). Positions there are rounded
# to 6 decimals, which is irrelevant at 1e-2 m error levels.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE="$(cd "$HERE/../.." && pwd)"

DIR="${1:-$WORKSPACE/results/final/triangulation_configs/sweep_dlt_nodesc}"
GTDIR="${2:-$WORKSPACE/experiments/results/ov_accuracy/gt}"
MD="${3:-0.02}"

EVAL_PY="${EVAL_ATE_PY:-$WORKSPACE/xivo/scripts/tum_rgbd_benchmark_tools/evaluate_ate.py}"
PYTHON="${EVAL_PYTHON:-$WORKSPACE/dependencies/venv/bin/python}"
OV_EVAL_BIN="${OV_EVAL_BIN:-$WORKSPACE/experiments/ov_build_eval/error_singlerun}"

echo "xivo dir : $DIR"
echo "gt dir   : $GTDIR"
echo "window   : $MD"
echo
printf '%-8s %-10s %-8s %-10s %-10s\n' seq ATE pairs ATE_ov_eval RPE_rot_deg
sum=0; n=0
for seq in room1 room2 room3 room4 room5 room6; do
  est="$DIR/tumvi_${seq}_cam0"
  gt="$GTDIR/$seq.txt"
  [ -f "$est" ] || { printf '%-8s %s\n' "$seq" "MISSING $est"; continue; }
  out=$("$PYTHON" "$EVAL_PY" "$gt" "$est" --verbose --max_difference "$MD")
  ate=$(echo "$out" | sed -n 's/^absolute_translational_error.rmse \([0-9.eE+-]*\).*/\1/p')
  pairs=$(echo "$out" | sed -n 's/^compared_pose_pairs \([0-9]*\).*/\1/p')
  ovout=$("$OV_EVAL_BIN" posyaw "$gt" "$est" 2>/dev/null || true)
  ov_ate=$(echo "$ovout" | sed -n 's/.*rmse_ori = [0-9.]* | rmse_pos = \([0-9.]*\).*/\1/p' | head -1)
  ov_rpe=$(echo "$ovout" | sed -n 's/^seg 8 - median_ori = \([0-9.]*\).*/\1/p' | head -1)
  printf '%-8s %-10s %-8s %-10s %-10s\n' "$seq" "$ate" "$pairs" "${ov_ate:--}" "${ov_rpe:--}"
  sum=$(python3 -c "print($sum + $ate)"); n=$((n + 1))
done
[ "$n" -gt 0 ] && python3 -c "print('\nmean over %d seq: %.4f' % ($n, $sum / $n))"
